/** @file   include/dmlite/common/config.h
 *  @brief  Header generated by CMake with the build configuration used.
 *  @author Automated generation
 */
#ifndef DMLITE_COMMON_CONFIG_H
#define DMLITE_COMMON_CONFIG_H

/* Version */
#define DMLITE_MAJOR @dmlite_MAJOR@
#define DMLITE_MINOR @dmlite_MINOR@
#define DMLITE_PATCH @dmlite_PATCH@

/* Host certificate */
#define HOST_CERTIFICATE "@HOST_CERTIFICATE@"

#endif /* DMLITE_COMMON_CONFIG_H */
